[package]
name = "rcloader"
version = "0.1.0"
authors = ["Hamid <hamid@fastforward.ai>"]
edition = "2018"

[dependencies]
json-patch = "*"
reqwest = "0.9.20"
base64 = "0.10.1"
itertools = "0.8.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }